import {
  LayoutDashboard,
  BarChart3,
  FolderKanban,
  Tags,
  Cpu,
  GalleryHorizontalEnd,
  Boxes,
  Workflow,
  Newspaper,
  LayoutTemplate,
  HelpCircle,
  FileStack,
  Building2,
  Quote,
  Users,
  Handshake,
  Target,
  FileSpreadsheet,
  MailOpen,
  Megaphone,
  MessageSquareWarning,
  MousePointerClick,
  Search,
  ListTree,
  Image,
  Settings,
  ShieldCheck,
  DatabaseBackup,
  ScrollText,
  Circle,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

const REGISTRY: Record<string, LucideIcon> = {
  LayoutDashboard,
  BarChart3,
  FolderKanban,
  Tags,
  Cpu,
  GalleryHorizontalEnd,
  Boxes,
  Workflow,
  Newspaper,
  LayoutTemplate,
  HelpCircle,
  FileStack,
  Building2,
  Quote,
  Users,
  Handshake,
  Target,
  FileSpreadsheet,
  MailOpen,
  Megaphone,
  MessageSquareWarning,
  MousePointerClick,
  Search,
  ListTree,
  Image,
  Settings,
  ShieldCheck,
  DatabaseBackup,
  ScrollText,
};

export function AdminIcon({ name, className }: { name: string; className?: string }) {
  const Cmp = REGISTRY[name] ?? Circle;
  return <Cmp className={cn("size-4", className)} aria-hidden />;
}
