import type { ResourceDef } from "./types";

const PUBLISH_STATUS = [
  { value: "DRAFT", label: "Rascunho" },
  { value: "SCHEDULED", label: "Agendado" },
  { value: "PUBLISHED", label: "Publicado" },
  { value: "ARCHIVED", label: "Arquivado" },
];

/**
 * Registro de recursos do motor de CRUD genérico.
 * Cada entrada vira automaticamente:
 *   /admin/<key>            (lista + busca + paginação)
 *   /admin/<key>/new        (criar)
 *   /admin/<key>/<id>       (editar / excluir / duplicar)
 */
export const RESOURCES: ResourceDef[] = [
  // ------------------------------------------------------------------ PROJETOS
  {
    key: "projetos",
    model: "project",
    labelSingular: "Projeto",
    labelPlural: "Projetos",
    icon: "FolderKanban",
    minRole: "EDITOR",
    listColumns: ["title", "category", "status", "featured", "order"],
    searchable: ["title", "excerpt", "clientName"],
    defaultSort: { field: "order", dir: "asc" },
    sortable: true,
    duplicable: true,
    fields: [
      { name: "title", label: "Título", type: "text", required: true, span: 2 },
      { name: "slug", label: "Slug", type: "slug", slugFrom: "title", required: true },
      { name: "status", label: "Status", type: "select", options: PUBLISH_STATUS, default: "DRAFT" },
      { name: "excerpt", label: "Resumo", type: "textarea", span: 2 },
      { name: "description", label: "Descrição", type: "richtext", span: 2 },
      { name: "objectives", label: "Objetivos", type: "richtext", span: 2, hideInList: true },
      { name: "results", label: "Resultados", type: "richtext", span: 2, hideInList: true },
      { name: "coverUrl", label: "Imagem de capa", type: "image" },
      { name: "videoUrl", label: "Vídeo (URL)", type: "text" },
      {
        name: "categoryId",
        label: "Categoria",
        type: "relation",
        relationTo: "category",
        relationLabel: "name",
      },
      {
        name: "clientId",
        label: "Cliente",
        type: "relation",
        relationTo: "client",
        relationLabel: "name",
      },
      { name: "clientName", label: "Cliente (texto livre)", type: "text", hideInList: true },
      { name: "tags", label: "Tags", type: "tags", span: 2 },
      { name: "liveUrl", label: "Link do projeto", type: "text" },
      { name: "githubUrl", label: "GitHub", type: "text" },
      { name: "behanceUrl", label: "Behance", type: "text", hideInList: true },
      { name: "dribbbleUrl", label: "Dribbble", type: "text", hideInList: true },
      { name: "featured", label: "Destaque", type: "boolean", default: false },
      { name: "recommended", label: "Recomendado", type: "boolean", default: false },
      { name: "order", label: "Ordem", type: "number", default: 0 },
      { name: "deliveredAt", label: "Entregue em", type: "date", hideInList: true },
    ],
  },

  // ---------------------------------------------------------------- CATEGORIAS
  {
    key: "categorias",
    model: "category",
    labelSingular: "Categoria",
    labelPlural: "Categorias",
    icon: "Tags",
    minRole: "EDITOR",
    listColumns: ["name", "slug", "order"],
    searchable: ["name", "slug"],
    defaultSort: { field: "order", dir: "asc" },
    sortable: true,
    fields: [
      { name: "name", label: "Nome", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", slugFrom: "name", required: true },
      { name: "description", label: "Descrição", type: "textarea", span: 2 },
      { name: "color", label: "Cor (hex)", type: "text" },
      { name: "icon", label: "Ícone (lucide)", type: "text" },
      { name: "order", label: "Ordem", type: "number", default: 0 },
    ],
  },

  // -------------------------------------------------------------- TECNOLOGIAS
  {
    key: "tecnologias",
    model: "technology",
    labelSingular: "Tecnologia",
    labelPlural: "Tecnologias",
    icon: "Cpu",
    minRole: "EDITOR",
    listColumns: ["name", "slug", "order"],
    searchable: ["name"],
    defaultSort: { field: "order", dir: "asc" },
    sortable: true,
    fields: [
      { name: "name", label: "Nome", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", slugFrom: "name", required: true },
      { name: "iconUrl", label: "Ícone (URL)", type: "image" },
      { name: "color", label: "Cor (hex)", type: "text" },
      { name: "order", label: "Ordem", type: "number", default: 0 },
    ],
  },

  // ------------------------------------------------------------------ SERVIÇOS
  {
    key: "servicos",
    model: "service",
    labelSingular: "Serviço",
    labelPlural: "Serviços",
    icon: "Boxes",
    minRole: "EDITOR",
    listColumns: ["title", "priceLabel", "featured", "enabled", "order"],
    searchable: ["title", "summary"],
    defaultSort: { field: "order", dir: "asc" },
    sortable: true,
    duplicable: true,
    fields: [
      { name: "title", label: "Título", type: "text", required: true, span: 2 },
      { name: "slug", label: "Slug", type: "slug", slugFrom: "title", required: true },
      { name: "icon", label: "Ícone (lucide)", type: "text" },
      { name: "summary", label: "Resumo", type: "textarea", span: 2 },
      { name: "description", label: "Descrição", type: "richtext", span: 2 },
      { name: "imageUrl", label: "Imagem", type: "image" },
      { name: "priceLabel", label: "Rótulo de preço", type: "text" },
      { name: "features", label: "Itens / entregáveis", type: "tags", span: 2 },
      { name: "ctaLabel", label: "Texto do botão", type: "text" },
      { name: "ctaHref", label: "Link do botão", type: "text" },
      { name: "featured", label: "Destaque", type: "boolean", default: false },
      { name: "enabled", label: "Ativo", type: "boolean", default: true },
      { name: "order", label: "Ordem", type: "number", default: 0 },
    ],
  },

  // ------------------------------------------------------------------- PROCESSO
  {
    key: "processo",
    model: "processStep",
    labelSingular: "Etapa",
    labelPlural: "Processo",
    icon: "Workflow",
    minRole: "EDITOR",
    listColumns: ["title", "order", "enabled"],
    searchable: ["title"],
    defaultSort: { field: "order", dir: "asc" },
    sortable: true,
    fields: [
      { name: "title", label: "Título", type: "text", required: true },
      { name: "icon", label: "Ícone (lucide)", type: "text" },
      { name: "description", label: "Descrição", type: "textarea", span: 2 },
      { name: "order", label: "Ordem", type: "number", default: 0 },
      { name: "enabled", label: "Ativo", type: "boolean", default: true },
    ],
  },

  // ------------------------------------------------------------------------ FAQ
  {
    key: "faq",
    model: "faqItem",
    labelSingular: "Pergunta",
    labelPlural: "FAQ",
    icon: "HelpCircle",
    minRole: "EDITOR",
    listColumns: ["question", "order", "enabled"],
    searchable: ["question", "answer"],
    defaultSort: { field: "order", dir: "asc" },
    sortable: true,
    fields: [
      { name: "question", label: "Pergunta", type: "text", required: true, span: 2 },
      { name: "answer", label: "Resposta", type: "richtext", required: true, span: 2 },
      {
        name: "categoryId",
        label: "Categoria",
        type: "relation",
        relationTo: "faqCategory",
        relationLabel: "name",
      },
      { name: "order", label: "Ordem", type: "number", default: 0 },
      { name: "enabled", label: "Ativo", type: "boolean", default: true },
    ],
  },

  // -------------------------------------------------------------------- CLIENTES
  {
    key: "clientes",
    model: "client",
    labelSingular: "Cliente",
    labelPlural: "Clientes",
    icon: "Building2",
    minRole: "EDITOR",
    listColumns: ["name", "segment", "featured", "order"],
    searchable: ["name", "segment"],
    defaultSort: { field: "order", dir: "asc" },
    sortable: true,
    fields: [
      { name: "name", label: "Nome", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", slugFrom: "name", required: true },
      { name: "logoUrl", label: "Logo", type: "image" },
      { name: "websiteUrl", label: "Site", type: "text" },
      { name: "segment", label: "Segmento", type: "text" },
      { name: "featured", label: "Destaque", type: "boolean", default: false },
      { name: "order", label: "Ordem", type: "number", default: 0 },
    ],
  },

  // ----------------------------------------------------------------- DEPOIMENTOS
  {
    key: "depoimentos",
    model: "testimonial",
    labelSingular: "Depoimento",
    labelPlural: "Depoimentos",
    icon: "Quote",
    minRole: "EDITOR",
    listColumns: ["authorName", "company", "rating", "featured", "enabled"],
    searchable: ["authorName", "company", "quote"],
    defaultSort: { field: "order", dir: "asc" },
    sortable: true,
    fields: [
      { name: "authorName", label: "Autor", type: "text", required: true },
      { name: "role", label: "Cargo", type: "text" },
      { name: "company", label: "Empresa", type: "text" },
      { name: "avatarUrl", label: "Foto", type: "image" },
      { name: "quote", label: "Depoimento", type: "textarea", required: true, span: 2 },
      { name: "rating", label: "Nota (1-5)", type: "number", default: 5 },
      {
        name: "clientId",
        label: "Cliente vinculado",
        type: "relation",
        relationTo: "client",
        relationLabel: "name",
      },
      { name: "featured", label: "Destaque", type: "boolean", default: false },
      { name: "enabled", label: "Ativo", type: "boolean", default: true },
      { name: "order", label: "Ordem", type: "number", default: 0 },
    ],
  },

  // ---------------------------------------------------------------------- EQUIPE
  {
    key: "equipe",
    model: "teamMember",
    labelSingular: "Membro",
    labelPlural: "Equipe",
    icon: "Users",
    minRole: "EDITOR",
    listColumns: ["name", "role", "enabled", "order"],
    searchable: ["name", "role"],
    defaultSort: { field: "order", dir: "asc" },
    sortable: true,
    fields: [
      { name: "name", label: "Nome", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", slugFrom: "name", required: true },
      { name: "role", label: "Cargo", type: "text", required: true },
      { name: "bio", label: "Bio", type: "textarea", span: 2 },
      { name: "avatarUrl", label: "Foto", type: "image" },
      { name: "email", label: "E-mail", type: "text" },
      { name: "linkedinUrl", label: "LinkedIn", type: "text" },
      { name: "githubUrl", label: "GitHub", type: "text" },
      { name: "order", label: "Ordem", type: "number", default: 0 },
      { name: "enabled", label: "Ativo", type: "boolean", default: true },
    ],
  },

  // ------------------------------------------------------------------- PARCEIROS
  {
    key: "parceiros",
    model: "partner",
    labelSingular: "Parceiro",
    labelPlural: "Parceiros",
    icon: "Handshake",
    minRole: "EDITOR",
    listColumns: ["name", "tier", "enabled", "order"],
    searchable: ["name"],
    defaultSort: { field: "order", dir: "asc" },
    sortable: true,
    fields: [
      { name: "name", label: "Nome", type: "text", required: true },
      { name: "logoUrl", label: "Logo", type: "image" },
      { name: "websiteUrl", label: "Site", type: "text" },
      {
        name: "tier",
        label: "Nível",
        type: "select",
        options: [
          { value: "standard", label: "Padrão" },
          { value: "gold", label: "Gold" },
          { value: "strategic", label: "Estratégico" },
        ],
        default: "standard",
      },
      { name: "order", label: "Ordem", type: "number", default: 0 },
      { name: "enabled", label: "Ativo", type: "boolean", default: true },
    ],
  },

  // --------------------------------------------------------------------- BANNERS
  {
    key: "banners",
    model: "banner",
    labelSingular: "Banner",
    labelPlural: "Banners",
    icon: "Megaphone",
    minRole: "EDITOR",
    listColumns: ["title", "placement", "enabled", "order"],
    searchable: ["title", "text"],
    defaultSort: { field: "order", dir: "asc" },
    sortable: true,
    fields: [
      { name: "title", label: "Título", type: "text", required: true, span: 2 },
      { name: "text", label: "Texto", type: "textarea", span: 2 },
      { name: "imageUrl", label: "Imagem", type: "image" },
      { name: "linkHref", label: "Link", type: "text" },
      { name: "linkLabel", label: "Texto do link", type: "text" },
      {
        name: "placement",
        label: "Posição",
        type: "select",
        options: [
          { value: "TOPBAR", label: "Barra superior" },
          { value: "HERO", label: "Hero" },
          { value: "INLINE", label: "Inline" },
          { value: "FOOTER", label: "Rodapé" },
        ],
        default: "TOPBAR",
      },
      { name: "bgColor", label: "Cor de fundo", type: "text" },
      { name: "textColor", label: "Cor do texto", type: "text" },
      { name: "startsAt", label: "Início", type: "date" },
      { name: "endsAt", label: "Fim", type: "date" },
      { name: "enabled", label: "Ativo", type: "boolean", default: true },
      { name: "order", label: "Ordem", type: "number", default: 0 },
    ],
  },

  // ---------------------------------------------------------------------- POPUPS
  {
    key: "popups",
    model: "popup",
    labelSingular: "Popup",
    labelPlural: "Popups",
    icon: "MessageSquareWarning",
    minRole: "EDITOR",
    listColumns: ["name", "trigger", "enabled"],
    searchable: ["name", "title"],
    fields: [
      { name: "name", label: "Nome interno", type: "text", required: true },
      { name: "title", label: "Título", type: "text", span: 2 },
      { name: "content", label: "Conteúdo (JSON)", type: "json", span: 2, default: {} },
      { name: "imageUrl", label: "Imagem", type: "image" },
      { name: "ctaLabel", label: "Texto do botão", type: "text" },
      { name: "ctaHref", label: "Link do botão", type: "text" },
      {
        name: "trigger",
        label: "Gatilho",
        type: "select",
        options: [
          { value: "ON_LOAD", label: "Ao carregar" },
          { value: "ON_DELAY", label: "Após X segundos" },
          { value: "ON_SCROLL", label: "Ao rolar X%" },
          { value: "ON_EXIT_INTENT", label: "Intenção de saída" },
        ],
        default: "ON_DELAY",
      },
      { name: "delaySeconds", label: "Delay (s)", type: "number", default: 6 },
      { name: "scrollPercent", label: "Scroll (%)", type: "number", default: 50 },
      {
        name: "frequency",
        label: "Frequência",
        type: "select",
        options: [
          { value: "once", label: "Uma vez (sempre)" },
          { value: "once-per-session", label: "Uma vez por sessão" },
          { value: "always", label: "Sempre" },
        ],
        default: "once-per-session",
      },
      { name: "enabled", label: "Ativo", type: "boolean", default: false },
    ],
  },

  // ------------------------------------------------------------------------- CTA
  {
    key: "cta",
    model: "cta",
    labelSingular: "CTA",
    labelPlural: "CTAs",
    icon: "MousePointerClick",
    minRole: "EDITOR",
    listColumns: ["key", "title", "variant", "enabled"],
    searchable: ["key", "title"],
    fields: [
      { name: "key", label: "Chave", type: "text", required: true, help: "ex: home-final" },
      { name: "eyebrow", label: "Sobre-título", type: "text" },
      { name: "title", label: "Título", type: "textarea", required: true, span: 2 },
      { name: "subtitle", label: "Subtítulo", type: "textarea", span: 2 },
      { name: "primaryLabel", label: "Botão primário — texto", type: "text" },
      { name: "primaryHref", label: "Botão primário — link", type: "text" },
      { name: "secondaryLabel", label: "Botão secundário — texto", type: "text" },
      { name: "secondaryHref", label: "Botão secundário — link", type: "text" },
      {
        name: "variant",
        label: "Estilo",
        type: "select",
        options: [
          { value: "PRIMARY", label: "Sólido" },
          { value: "SECONDARY", label: "Vidro" },
          { value: "GHOST", label: "Ghost" },
          { value: "GRADIENT", label: "Gradiente" },
        ],
        default: "GRADIENT",
      },
      { name: "enabled", label: "Ativo", type: "boolean", default: true },
    ],
  },

  // ------------------------------------------------------------------------- SEO
  {
    key: "seo",
    model: "seoMeta",
    labelSingular: "Meta SEO",
    labelPlural: "SEO por rota",
    icon: "Search",
    minRole: "EDITOR",
    listColumns: ["path", "title", "robots"],
    searchable: ["path", "title", "description"],
    fields: [
      { name: "path", label: "Rota", type: "text", required: true, help: "ex: / ou /portfolio" },
      { name: "title", label: "Title", type: "text", span: 2 },
      { name: "description", label: "Description", type: "textarea", span: 2 },
      { name: "keywords", label: "Keywords", type: "tags", span: 2 },
      { name: "canonicalUrl", label: "Canonical", type: "text" },
      { name: "robots", label: "Robots", type: "text", default: "index,follow" },
      { name: "ogTitle", label: "OG Title", type: "text" },
      { name: "ogDescription", label: "OG Description", type: "textarea", span: 2 },
      { name: "ogImageUrl", label: "OG Image", type: "image" },
      { name: "twitterCard", label: "Twitter Card", type: "text", default: "summary_large_image" },
      { name: "structuredData", label: "JSON-LD (schema.org)", type: "json", span: 2 },
    ],
  },

  // ------------------------------------------------------------------------ BLOG
  {
    key: "blog",
    model: "post",
    labelSingular: "Post",
    labelPlural: "Blog",
    icon: "Newspaper",
    minRole: "EDITOR",
    listColumns: ["title", "status", "featured", "publishedAt"],
    searchable: ["title", "excerpt"],
    defaultSort: { field: "createdAt", dir: "desc" },
    duplicable: true,
    fields: [
      { name: "title", label: "Título", type: "text", required: true, span: 2 },
      { name: "slug", label: "Slug", type: "slug", slugFrom: "title", required: true },
      { name: "status", label: "Status", type: "select", options: PUBLISH_STATUS, default: "DRAFT" },
      { name: "excerpt", label: "Resumo", type: "textarea", span: 2 },
      { name: "content", label: "Conteúdo", type: "richtext", span: 2, required: true },
      { name: "coverUrl", label: "Capa", type: "image" },
      { name: "readingTime", label: "Tempo de leitura (min)", type: "number" },
      {
        name: "categoryId",
        label: "Categoria",
        type: "relation",
        relationTo: "postCategory",
        relationLabel: "name",
      },
      { name: "featured", label: "Destaque", type: "boolean", default: false },
      { name: "publishedAt", label: "Publicado em", type: "date" },
    ],
  },

  // --------------------------------------------------------------- LANDING PAGES
  {
    key: "landing-pages",
    model: "landingPage",
    labelSingular: "Landing Page",
    labelPlural: "Landing Pages",
    icon: "LayoutTemplate",
    minRole: "EDITOR",
    listColumns: ["title", "slug", "status", "publishedAt"],
    searchable: ["title", "slug"],
    defaultSort: { field: "createdAt", dir: "desc" },
    duplicable: true,
    fields: [
      { name: "title", label: "Título", type: "text", required: true, span: 2 },
      { name: "slug", label: "Slug", type: "slug", slugFrom: "title", required: true },
      { name: "status", label: "Status", type: "select", options: PUBLISH_STATUS, default: "DRAFT" },
      {
        name: "blocks",
        label: "Blocos (JSON)",
        type: "json",
        span: 2,
        default: [],
        help: "Array de blocos { type, props }. O renderizador público interpreta cada bloco.",
      },
      { name: "theme", label: "Tema (JSON)", type: "json", span: 2, hideInList: true },
      { name: "publishedAt", label: "Publicado em", type: "date" },
    ],
  },
];

export function getResource(key: string): ResourceDef | undefined {
  return RESOURCES.find((r) => r.key === key);
}
